#pragma once

#define VIAL_KEYBOARD_UID {0xD4, 0xDC, 0x8D, 0x39, 0x17, 0xDD, 0xC4, 0x06}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 14}

// Activate Command with Left Ctrl + Right Ctrl.
#define IS_COMMAND() (get_mods() == MOD_MASK_CTRL)

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define DYNAMIC_KEYMAP_MACRO_COUNT 6
#define VIAL_KEY_OVERRIDE_ENTRIES 3
#define VIAL_COMBO_ENTRIES 3
#define VIAL_TAP_DANCE_ENTRIES 3
